### ISSUE TITLE
Remove Consumer.java

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.Android#1]
[Consumer.java](https://github.com/Azure/Azure.Android/blob/master/azuredata/src/main/java/com/azure/data/util/Consumer.java) needs to be removed from the project.  It can only be released under the GNU General Public License version 2.  We must comply with MIT.

**Comment by NateRickard** [comment]
Removed our consumer.java and used the built in interface instead.  This will result in requiring API level 24+ in order to leverage Java callback helper 'onCallback', but it's unclear if this will result in changing the min SDK for the library.
