### ISSUE TITLE
feature request - query to return only selected fields

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#102]
hi all, would be awesome if we could query (as we can now) but, only receive pre-nominated fields in the payload.

for example:
```SELECT c.id, c.roundDate FROM c where c.type = "round"```

so in this example we would only get back 2 fields - ```c.id``` and ```c.roundDate```

This would be a huge help in 2 key areas:
1. payload size can drop dramatically (eg. the doc above might have 100 fields etc., 98 of which we dont need in the given query response payload) 
2. RU costs will/may also greatly benefit (in this example against a real data set, our RU charge for the query would reduce from 28.320RU to 9.2RU !!).

**Comment by NateRickard** [comment]
@SogoGolf just pushed v0.2.7 which should support this.  Some notes:

- You can no longer create a query with `Query()`, you have to use `Query.select()` or `Query.select("property1", "property2", ...)`.  This was always intended and just not enforced.
- The query will still return results in the form of your document type.  That is, it will return results in a list using the doc type you specify; however, *only* the properties you queried for will be set on each doc.  We could eventually maybe return a Map or something if it would be more useful, but the internals would need to be changed quite a bit to support that, and you can pretty easily remap the results as is.

**Comment by SogoGolf** [comment]
hey @NateRickard , wow that was quick! i'll have time to look at testing this in next few days. awesome stuff many thanks.
