### ISSUE TITLE
replaceDocument is failing - Resource not found in classpath: kotlin/ranges/ranges.kotlin_builtins

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#104]
hi @NateRickard i'm seeing an exception when trying to replace a document.  the localised error desc is: ```Resource not found in classpath: kotlin/ranges/ranges.kotlin_builtins```

I can't really tell from that msg what the cause is but might it be a partition key error ?

```
AzureData.replaceDocument (document, COSMOS_COLLECTION_NAME, COSMOS_DATABASE_NAME) {
            if (it.isSuccessful) {
               //etc....
                finish()
            } else {
                Log.i(TAG, it.error?.localizedMessage)
            }
        }
```

**Comment by SogoGolf** [comment]
hmm I'm on 0.2.3 maybe that's it.  ill update now to 0.2.8 and try again.

**Comment by SogoGolf** [comment]
yep that was it sorry about that. closing the ticket

**Comment by NateRickard** [comment]
glad that was it!
