### ISSUE TITLE
add query support for ARRAY_LENGTH

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#106]
### Feature Summary

support for queries that use the ARRAY_LENGTH qualifier, eg. from the SQL API JS syntax:

```SELECT count(c.id) as rounds18Count FROM c where c.type = "round" and ARRAY_LENGTH(c.holeScores) = 18 and c.isDeleted = false```

provide that same capability in the Azure.Android query API

**Comment by NateRickard** [comment]
@SogoGolf I've implemented a generic way to support this and other functions in 0.4.0 (building now): `whereFunction()` and it associated variations. The main overloads will support a function such as ARRAY_LENGTH that takes a single arg, though you can also pass a list of args to the overload that does all of the work.

So, the above call can be achieved with something like:

```
Query.select(<args>)
   .from(<collection id>)
   .where("type", "round")
   .andWhereFunction("ARRAY_LENGTH", "holeScores", 18)
   .andWhere("isDeleted", false)
```

Let me know if you use it!
