### ISSUE TITLE
Android -CosmosDB : AzureData.getDocument() API call fails to return document

### ISSUE THREAD

**Issue by Raysapps** [Azure/Azure.Android#107]
I've successfully configured (AzureData.Configure()) and also created a database.
However, I am unable to access the document from the existing collection using the API AzureData.getDocument().
This API is returning the error " {"code": "NotFound", "message": "Entity with the specified id does not exist in the system}" Please help me with suggestions in this regard

**Comment by NateRickard** [comment]
That result is standard from the REST api if the document with that Id can't be found in the collection/db specified.

Can you share the pertinent bits of your code (without private data like keys, etc., of course)?

Can you also verify:

- You're using the latest version of the library (0.3.0)
- Are you using a master key to connect to Cosmos DB, or a permission provider?
  -  If using a key, you may want to generate a new key to rule out anything to do with that
- The Db and collection exist in your cosmos account, and you can find the document in the Azure portal via the data explorer (a screen cap of this would help)
  -  Can you get the Db and collection using this library? If not, this points to a setup issue or something amiss with the connection to your Cosmos DB environment
  -  Does the collection have a partition key? (If you created it via the Azure portal recently, it should). This library is designed to work with partitioned collections, though there are some deprecated API members that don't include it. If the collection has a partition key, then you must also use the partition key when retrieving the document. (See [this test](https://github.com/Azure/Azure.Android/blob/250ebd514a118c05c5fbfe0eee771e6a93c22884/azuredata/src/androidTest/java/com/azure/data/integration/DocumentTestsBase.kt#L248) to see the call with/without partition key)

It may help to review the [example apps](https://github.com/Azure/Azure.Android/tree/master/Example) to make sure there's nothing missing or out of place within your code, setup-wise. (Though, note that they've not been updated to account for the partition key requirement noted above).

**Comment by Raysapps** [comment]
Hi Nate,
Not really sure what I was doing wrong before, now I've fetched the documents and the API call AzureData.getdocuments() returned all the doc ids.

I am using the latest 0.3.0 library and the cosmosDB read-only key in Azure.Configure() method.
CosmosDB collection has a partitionkey and called the AzureData.getdocument() API version that takes the partition key variable.
This issue cannot be reproduced.
Please close the issue and Thank you for your support.

**Comment by NateRickard** [comment]
Great to hear it's working :)
