### ISSUE TITLE
AzureData -> AzureCore (refactor): default HTTP headers + user agent

### ISSUE THREAD

**Issue by NateRickard** [Azure/Azure.Android#11]
Goal: Refactor base/default http headers into the AzureCore library.

- [x] This will likely be dependent on #10 
- [x] [default HTTP headers + user agent](https://github.com/Azure/Azure.Android/blob/f830ec71a2aa828e2112a75db41387dea3b014f3/azuredata/src/main/java/com/azure/data/services/DocumentClient.kt#L24) should be moved (and/or replaced/refactored) to AzureCore 
- [x] [x-ms-version](https://github.com/Azure/Azure.Android/blob/f830ec71a2aa828e2112a75db41387dea3b014f3/azuredata/src/main/java/com/azure/data/services/DocumentClient.kt#L69) should be removed from this code
- [x] It's currently [hard-coded](https://github.com/Azure/Azure.Android/blob/f830ec71a2aa828e2112a75db41387dea3b014f3/azuredata/src/main/java/com/azure/data/services/DocumentClient.kt#L56) to get the library's version using `BuildConfig`.  Need to decide if this is the proper way to pull the lib's version or if we need to do this another way, etc.
- [x] Creating the user-agent is fairly expensive, so it should only be created once and cached (currently this is done via a Kotlin `by lazy` property)
- [x] Update [DocumentClient](https://github.com/Azure/Azure.Android/blob/f830ec71a2aa828e2112a75db41387dea3b014f3/azuredata/src/main/java/com/azure/data/services/DocumentClient.kt#L1027) to use functionality AzureCore adding [x-ms-version](https://github.com/Azure/Azure.Android/blob/f830ec71a2aa828e2112a75db41387dea3b014f3/azuredata/src/main/java/com/azure/data/services/DocumentClient.kt#L69) here

**Comment by colbylwilliams** [comment]
iOS implementation for reference:

- [DateFormat][0] (AzureCore)
- [HttpHeader][1] (AzureCore)
- [HttpMethod][2] (AzureCore)
- [HttpStatusCode][3] (AzureCore)
- [MSHttpHeader][4] (AzureData)
- [DocumentClientExtensions][5] (AzureData)

[0]:https://github.com/Azure/Azure.iOS/blob/master/AzureCore/Source/DateFormat.swift
[1]:https://github.com/Azure/Azure.iOS/blob/master/AzureCore/Source/HttpHeader.swift
[2]:https://github.com/Azure/Azure.iOS/blob/master/AzureCore/Source/HttpMethod.swift
[3]:https://github.com/Azure/Azure.iOS/blob/master/AzureCore/Source/HttpStatusCode.swift
[4]:https://github.com/Azure/Azure.iOS/blob/master/AzureData/Source/MSHttpHeader.swift
[5]:https://github.com/Azure/Azure.iOS/blob/master/AzureData/Source/DocumentClientExtensions.swift

**Comment by NateRickard** [comment]
4e8baa1f04044f55251d1ac98908d94f4924f314
