### ISSUE TITLE
Validate Resource Ids

### ISSUE THREAD

**Issue by NateRickard** [Azure/Azure.Android#15]
Every resource within an Azure Cosmos DB database account needs to have a unique identifier. Unlike ResourceId, which is set internally, this Id is settable by the user and is not immutable.

The AzureData SDK should validate the ID set by the user meets the following requirements before attempting to write the resource remotely:
- Resource IDs must not exceed 255 characters
- The following characters are restricted and cannot be used in the Id property: '/', '\', '?', '#'

This is currently partially implemented [here](https://github.com/Azure/Azure.Android/blob/f830ec71a2aa828e2112a75db41387dea3b014f3/azuredata/src/main/java/com/azure/data/util/StringExtensions.kt#L14)

**Comment by colbylwilliams** [comment]
iOS implementation for reference:
- [`ResourceValidation`](https://github.com/Azure/Azure.iOS/blob/master/AzureData/Source/Resources/ResourceValidation.swift)

**Comment by NateRickard** [comment]
implemented in 352aeac5bd1211ef38b057bd3ace83bd45bc273f
