### ISSUE TITLE
Add additional metadata to Response object

### ISSUE THREAD

**Issue by NateRickard** [Azure/Azure.Android#19]
Add [metadata](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.resourceresponse-1?view=azure-dotnet) to response object

**Comment by NateRickard** [comment]
Resource: [Common Azure Cosmos DB REST response headers](https://docs.microsoft.com/en-us/rest/api/documentdb/common-documentdb-rest-response-headers)

**Comment by johnnylambada** [comment]
@NateRickard Do you need more fields from the "Common Azure Cosmos DB REST response headers" to here? Or something else: https://github.com/Azure/Azure.Android/blob/65cf2aedc3bd4b27eddef9781a7a5cb61118c144/azuredata/src/main/java/com/azure/data/service/ResourceResponse.kt#L13-L21
