### ISSUE TITLE
AzureCore Library Dependencies: Secure Storage

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.Android#2]
Determine best **MIT Licensed** OSS library to provide functionality exposed in AzureCore.

List suggested libraries in comments for review and final decision.

**Comment by NateRickard** [comment]
Options & supporting libs:

- [R2D2](https://github.com/moldedbits/r2d2)
- [Armadillo](https://github.com/patrickfav/armadillo)
- [Conceal](https://github.com/facebook/conceal)
  -  [Introducing Conceal](https://code.facebook.com/posts/1419122541659395/introducing-conceal-efficient-storage-encryption-for-android/)
  -  BSD licensed
- [BR Vault](https://github.com/BottleRocketStudios/Android-Vault)
- [Secure Device Storage](https://github.com/adorsys/secure-storage-android)

**Comment by colbylwilliams** [comment]
@johnnylambada do you have a preference/feedback on any of these libraries?

**Comment by johnnylambada** [comment]
r2d2

- single contributor
- name is problematic
- I don't see a license
- last commit over 9 months ago
- 25 stars
 
Armadillo

- single contributor
- Apache license
- active development
- 25 stars
- nice documentation
- nice builder approach
- looks like it integrates nicely with SharePreferences

Conceal

- facebook
- bsd license
- 2600 stars
- good doc
- looks like it requires openssl C library
- worth a closer look

BR Vault

- 49 stars
- being maintained but not under active dev
- Apache license

Secure Device Storage

- 125 stars
- not under active dev
- apache license
- doc looks good

It looks like any of them will cover secure shared preferences, some will secure files as well. It's probably worth looking at conceal, secure device storage Armadillo and BR vault in that order. I'd leave r2d2 alone. It looks like conceal requires the NDK so has a C library (probably openssl). This will blow up our package size, so we probably want to avoid that.

**Comment by NateRickard** [comment]
@johnnylambada good feedback... @colbylwilliams and I had discussed some other reasons for not using conceal as well so kinda agree there.  Are you aware of any other options?  I just took a few from android arsenal but I was a little surprised to not see something more 'prominent' in the space outside of conceal (more stars, activity, etc.)
