### ISSUE TITLE
Implement reachability monitoring and logic

### ISSUE THREAD

**Issue by NateRickard** [Azure/Azure.Android#30]
Related to #4

Re: https://azuremobile.slack.com/archives/C9X9NUP9T/p1523370455000158

>right, my understanding is best practice is to not let the current reachability state determine whether or not to make a call — instead we should _always_ make the attempt.  Is there a notification you can subscribe to on android for with the reachability changes state?
so it should work like this:
>- subscribe to reachability change event
 >- always attempt to make calls without checking reachability
>- if a request fails do to network being unreachable, the set an “offline” flag and don’t make requests attempts again until…
>- you get the reachability changed event, then _that’s_ when we give the request another shot
>- if it fails, keep the offline flag, if it succeeds, remove the offline flag
so we shouldn’t depend/check on the reachability directly, but when a request fails with an error saying it couldn’t hit the network, then assume offline and wait for something to change

As with logging, it would be good to have the reachability code abstracted away in Core since this functionality may need to be reused across other modules.

**Comment by johnnylambada** [comment]
Regarding the notification for network state on Android. It seems that there are several APIs at work depending on the Android API version in use. 
- API 21 gives us [ConnectivityManager.registerDefaultNetworkCallback](https://developer.android.com/reference/android/net/ConnectivityManager.html#registerDefaultNetworkCallback(android.net.ConnectivityManager.NetworkCallback)) with callbacks like onAvailable/onUnavailable & onLosing/onLost. This API requires the [ACCESS_NETWORK_STATE](https://developer.android.com/reference/android/Manifest.permission.html#ACCESS_NETWORK_STATE)
- On APIs below 24 we can register a BroadcastReceiver for [CONNECTIVITY_ACTION](https://developer.android.com/reference/android/net/ConnectivityManager.html#CONNECTIVITY_ACTION). 
- It's possible that below API 17 we may run into more trouble, but we could just bump the minimum API to get around this or version 1.0.
- The [Managing Network Usage](https://developer.android.com/training/basics/network-ops/managing.html) goes into some detail about this topic.

So for now, I'm going to implement ConnectivityManager.registerDefaultNetworkCallback and then if there's time the CONNECTIVITY_ACTION BroadcastReceiver.

**Comment by johnnylambada** [comment]
I looked at the iOS code -- it's using the ReachabilityManager from AlamoFire. It's pretty comprehensive, so I decided to take a quick look at what's available for Android before rolling our own. Here's what I found:
* https://github.com/pwittchen/ReactiveNetwork (1773 stars. Requires rx-java. Has a kotlin app)
* https://github.com/novoda/merlin (386 stars)
* https://github.com/has-taiar/Reachability.Net (22 stars)
* https://gist.github.com/emil2k/5130324 A simple class in a gist
* https://github.com/quemb/Reachability (0 stars)
The top two look the most promising. ReactiveNetwork looks pretty heavy requiring RxJava.

**Comment by NateRickard** [comment]
@johnnylambada Yes let's do that.  Definitely want to avoid a dependency on RxJava IMO - too many devs not using that to force it on ppl.
