### ISSUE TITLE
AzureCore Library Dependencies: Logging

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/Azure.Android#5]
Determine best **MIT Licensed** OSS library to provide functionality exposed in AzureCore.

List suggested libraries in comments for review and final decision.

**Comment by NateRickard** [comment]
[Gson](https://github.com/google/gson)
[OkHttp](http://square.github.io/okhttp/)

Both are Apache-licensed...

**Comment by NateRickard** [comment]
[List of common logging libs](https://android-arsenal.com/tag/57)

Options:

- [Hugo](https://github.com/JakeWharton/hugo)
  -  Method call logging, automated by annotations
  -  Apache licensed
- [Timber](https://github.com/JakeWharton/timber)
  -  Wrapper for Android logs, allows different log 'trees' based on config, etc.
  -  Apache licensed
  -  [Kotlin extensions](https://github.com/ajalt/timberkt)
- [logback-android](https://github.com/tony19/logback-android)
  -  Supports many log destinations
- [LoggingInterceptor](https://github.com/ihsanbal/LoggingInterceptor)
  -  For OkHttp logging of request/response
  -  MIT licensed
- [kotlin-logging](https://github.com/MicroUtils/kotlin-logging)
  -  Kotlin-based
  -  Wrapper for SL4J

**Comment by NateRickard** [comment]
Leaning toward using the OkHttp interceptor - seems like an easy way to get debug logging for all of the API calls.

For general logging, Timber + Kotlin extensions seems like a good fit.

**Comment by colbylwilliams** [comment]
@johnnylambada do you have a preference/feedback on any of these libraries?

**Comment by johnnylambada** [comment]
Hugo might be interesting, we can try it easily enough.

I agree with okhttp-interceptor, I use it all the time.

Timber is great -- I've used it. The kotlin extensions look good too but lose a lot of the lint checks. The lint checks are probably not as important for kotlin so it's not a big deal.  The problem with Timber is it likes to be instantiated in the Application class, and I don't know if we currently have any requirement for our library to be instantiated in the Application class. It also might interfere with the user's timber setup.

logback-android looks a bit heavy

kotlin-logging looks lightweight

I'll try out a few of them and let you know my findings.
