### ISSUE TITLE
AzureData - No way to add our own type adapters to Gson 

### ISSUE THREAD

**Issue by skela** [Azure/Azure.Android#64]
Could you expose a way for us to add our own type adapters to the the gson instance used by the library?

It would save me from having to add a bunch of boiler plate for things like enums (among other things). I'm sure there are other uses where it would or could be useful.

**Comment by NateRickard** [comment]
Fixed in #72 

@skela Can you review and see if this handles your concerns?  Added an optional callback during .configure() that will allow you to do anything you want to the GsonBuilder
