### ISSUE TITLE
Requirement for android 24 - can this be excluded???

### ISSUE THREAD

**Issue by alexdoan102** [Azure/Azure.Android#74]
*Only submit issues here for the Android SDKs -- Issues in the deployment template and functions should be submit in aka.ms/mobile*

If you are creating an issue for a **BUG** please fill out the applicable information below. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and link to it here.

## Bug Information

 most of the android tablets still run on android 21. Can you please remove the requirement to target android 24 (because of your usage of android lambda notation requiring android7 ). We would like to use your sdk....but android 24 is no good for most people still on Android 21 (5.0)

**Comment by NateRickard** [comment]
@alexdoan102 this is not a hard requirement.  The min SDK for the lib itself is 16.  API 24 is needed if you want to use it from Java and want to use the OnCallback feature described [here](https://github.com/Azure/Azure.Android/tree/master/azuredata#using-from-java).  I just spun up a Nexus 7 tablet with system image at API 22 (5.1), and the example app is running ok.

**Comment by wikes82** [comment]
@NateRickard  on Android 5.1 (API 22) whenever I tried to use offline mode and create document, it throw error : java.lang.NoSuchMethodError: No interface method getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/Map; or its super classes (declaration of 'java.util.Map' appears in /system/framework/core-libart.jar) 

CreateDocument offline  works fine on API > 24

**Comment by NateRickard** [comment]
Thanks for the specific feedback @wikes82.  Looks like there's a special case for getOrDefault(): https://youtrack.jetbrains.com/issue/KT-20358

I've reimplemented that logic internally in the project and now have passing offline tests when running on my API 22 device.  Fixed in ec467f5ea12650b764ce27a552e75a832243397b and packaged as 0.1.2
