### ISSUE TITLE
orderby not working

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#79]
## Bug Information
Trying to sort a collection by string ("name"). Doesn't work, in that the result set just returns the first X documents in the given collection. ".orderBy" seems to be ignored.

See the attached screenshot from portal. You'll see the first doc in the collection (with no order by applied) is name = "Boonah Golf Club". 

Applying the order by in the code snippet below does nothing. The same default result set (ie without any order by applied) is returned.

### Expected Result
The first document in the sorted query should be "1770 Golf Club".

### Code snippet
        val query = Query.select()
        .from("clubs")
        .orderBy("name", true) 

        AzureData.queryDocuments ("clubs", "sogodb", query, CustomDocumentAzure::class.java) {
            for (doc in it.resource?.items!!) {
                Log.i("AZURE", "${doc!!.name}")
            }
        }

### Screenshots

![image](https://user-images.githubusercontent.com/19580787/52023786-9e9ac580-2552-11e9-80c3-5dc805b04fa7.png)

![image](https://user-images.githubusercontent.com/19580787/52023953-1b2da400-2553-11e9-8652-ab499e91b02f.png)

**Comment by SogoGolf** [comment]
hi all, just checking in on this ticket, have you been able to repro it ?

**Comment by NateRickard** [comment]
I just pushed a commit that should fix this... however, there's still work to be done, as apparently cross partition queries are not supported with an order by clause without some extra work.  I'm going to work on this scenario and when I have a passing test for that as well I'll push out a new release.

**Comment by SogoGolf** [comment]
awesome stuff thanks so much @NateRickard

**Comment by NateRickard** [comment]
fyi PR #88 should solve that scenario (described here: https://stackoverflow.com/questions/50240232/cosmos-db-rest-api-order-by-with-partitioning)

**Comment by SogoGolf** [comment]
hi @NateRickard I just tested this and didn't see correct sort order results. wondering if i jumped in a bit early and this isn't released yet ?

```    
implementation 'com.azure.android:azuredata:0.2.0'
```

```
            val query = Query.select()
                .from("sogocollection")
                .where("type", "club")
                .orderBy("name", true)


            AzureData.queryDocuments ("sogocollection", "sogodb", query, GolferDocument::class.java) {
                val documents = it.resource?.items
                documents?.forEach {
                    Log.i("AZURE", "${it.name}")
                }
            }

```

output snippet:
```
AZURE: 
  ...
   Balingup Golf Club
    Balgowlah Golf Club
    Balaklava Golf Club
    Aussie Golf Ranch
    Augusta Golf Club
    Augathella Golf Club
    Atherton Golf Club
    Asquith Golf Club
    ... (more "A" here..)
    Alexandra Golf Club
    Albert Park Golf Course
    Aberdeen Golf Club
    Bakers Hill Golf Club
    Baker Golf Club
    Bairnsdale Golf Club
    Badgingarra Golf Club
   ...
```

this is from portal against same data set:
![image](https://user-images.githubusercontent.com/19580787/53310844-a146cb80-3902-11e9-96d2-853c81f392fc.png)

**Comment by NateRickard** [comment]
My bad, never followed thru with releasing an updated version.  I just pushed 0.2.1, which should have the changes.

**Comment by SogoGolf** [comment]
gradle update -> build -> booyaa!  worked nicely thanks @NateRickard
