### ISSUE TITLE
delete specific document by id - failed

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#81]
## Bug Information

trying to delete a single document by id.

            AzureData.deleteDocument ("golfer_c44a0553-b3fd-4236-aa40-0d7c0d95a533", "sogocollection", "sogodb") {
                Log.i("AZURE", "delete worked? ${it.isSuccessful} ${it.error}")
            }

### Actual Behavior

the callback error message from above is:
      ```delete worked? false```
           
{"code":"BadRequest","message":"Message: {\"Errors\":[\"The partition key supplied in x-ms-   partitionkey header has fewer components than defined in the the collection.\"]}\r\nActivityId: 65b6f251-68c2-4450-83ef-fba3aa2d09ef, Request URI: /apps/8e606766-2bd8-4f11-a1c3-34b3c65ac48a/services/8f43c3c6-d642-4eae-9102-db1d938d1d17/partitions/cae4ccad-0a7e-4a8f-bba5-7d4b34b2a4b2/replicas/131938222164198417p/, RequestStats: \r\nRequestStartTime: 2019-02-07T01:43:37.7284573Z, RequestEndTime: 2019-02-07T01:43:37.7284573Z, Number of regions attempted: 1\r\nResponseTime: 2019-02-07T01:43:37.7284573Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-australiaeast1-fd4.documents.azure.com:14034/apps/8e606766-2bd8-4f11-a1c3-34b3c65ac48a/services/8f43c3c6-d642-4eae-9102-db1d938d1d17/partitions/cae4ccad-0a7e-4a8f-bba5-7d4b34b2a4b2/replicas/131938222164198417p/, LSN: 337, GlobalCommittedLsn: 337, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 1001, RequestCharge: 0, ItemLSN: -1, SessionToken: 337, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Delete\r\n, SDK: Microsoft.Azure.Documents.Common/2.1.0.0"}

**Comment by NateRickard** [comment]
This looks like it was also due to the partition key change.  Should be fixed via #86 and in v0.2.0.  @SogoGolf would appreciate if you can confirm in latest.

**Comment by SogoGolf** [comment]
Thanks @NateRickard I'll test this tom.

**Comment by SogoGolf** [comment]
hi @NateRickard i tested this and came across one issue. firstly deleting a doc that does have a partition key value, works fine.

however trying to delete a doc that has NO partition key value fails, with error "code":"NotFound" "message": "Entity with the specified id does not exist in the system.

the interesting thing to me was that the nodejs API (which i used to pop a couple of test docs into the collection) let me add documents with NO partition key value, to a collection where a partition key has been specified (which is now required anyway). my immediate thought was shouldn't the nodejs api not allow me to add a document, when a partition key property/value, is not provided ? or if this is allowed, then the Android api should handle this scenario.

here's a pic of what i mean:

![image](https://user-images.githubusercontent.com/19580787/53208967-fa0d2e80-368c-11e9-8894-beb25437190e.png)

**Comment by NateRickard** [comment]
that doesn't sound right re: the node sdk behavior.  A collection that has a partition key defined should give you the same error you saw in #75 ("The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.").  I wonder if they're sending a blank string as the value in those cases or something?

If you want to try deleting a doc w/o a partition key you would need to define a collection w/o one - which you can only do via the SDK(s) now.  Partition key-less tests can be found [here](https://github.com/Azure/Azure.Android/blob/master/azuredata/src/androidTest/java/com/azure/data/integration/CustomDocumentTests.kt), and we do have a passing test for deleting by Id from a collection w/o a partition key.

**Comment by SogoGolf** [comment]
totally agree re the nodejs sdk not sure why it was allowing that. i think nodejs api caused the issue in this example.
