### ISSUE TITLE
geolocation query

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#83]
is it possible to make a geolocation query from this Android api ? i couldn't see query params for it but wanted to check.

for example can this be achieved ? 
```
SELECT f.id 
FROM f 
WHERE ST_DISTANCE(f.location, {'type': 'Point', 'coordinates':[151.2357330322266, -33.77001515278013]}) < 30000 
```

**Comment by NateRickard** [comment]
@SogoGolf added native support for geo objects Point, LineString, and Polygon + query support for distance, intersection, and within functions.  Available in 0.2.4.
