### ISSUE TITLE
Access query data whilst offline

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#84]
query ❌ FAILURE is returned if a query is called whilst the device is offline

is this expected behaviour based on the Preview Release API's ? we cant really use Azure.Android offline without the ability to query the locally sync'd data, or minimally, re-access data previously returned from a query (when online)

**Comment by NateRickard** [comment]
@SogoGolf just implemented the same support on android that was recently added to iOS.  Tests are passing but let us know how it goes as you start using it.

**Comment by SogoGolf** [comment]
awesome stuff thanks @NateRickard . I'll definitely add this in for testing over the next few days and will keep you posted

**Comment by SogoGolf** [comment]
@NateRickard i just ran a quick test and the offline query didn't work. did you need to bump the version to 0.2.4 ?

**Comment by NateRickard** [comment]
Yes this has not been released yet, waiting to add some of the geospatial features as well.  I'll let you know.

**Comment by NateRickard** [comment]
@SogoGolf added native support for geo objects Point, LineString, and Polygon + query support for distance, intersection, and within functions.  Available in 0.2.4.

**Comment by SogoGolf** [comment]
brilliant @NateRickard will test this next few days
