### ISSUE TITLE
unparsable error using Date() type in model class

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#93]
we've got a document with date of birth field that is stored as an ISO string. when trying to run a query the android app throws exception trying to convert the (iso) date string to the AzureData class object. 

 CosmosDB object:

```
{
      .... other fields,
      "dateOfBirth": "1985-01-29T13:00:00.000Z",
}
```

kotlin class on Droid:
```
class GolferDocument(id: String? = null) : Document(id) {
    ....
    var dateOfBirth: Date = Date()
}
```

exception msg:
```
Unparseable date: "1985-01-29T13:00:00.000Z" (at offset 23)
```

**Comment by NateRickard** [comment]
If you're dealing with dates in your existing data with a specific format, you can create a [Gson type adapter](https://google.github.io/gson/apidocs/com/google/gson/TypeAdapter.html) to make the conversion.  Look at the existing date converter [here](https://github.com/Azure/Azure.Android/blob/master/azurecore/src/main/java/com/azure/core/util/DateTypeAdapter.kt).  To register your adapter, you can use the callback in the `AzureData.configure()` call.  See the [custom type adapter test](https://github.com/Azure/Azure.Android/blob/master/azuredata/src/androidTest/java/com/azure/data/integration/CustomTypeAdapterTests.kt) to see this in action (sorry, docs lagging behind).

**Comment by SogoGolf** [comment]
thanks @NateRickard ill give this a try.
