### ISSUE TITLE
createDocument, updateDocument, storedProcedure operations fail due to missing partition key header

### ISSUE THREAD

**Issue by SogoGolf** [Azure/Azure.Android#94]
hi @NateRickard , i came across the same partition key error today in our android app for:
```
.createDocument(xxx...)
and
.replaceDocument(xxx...)
and
.executeStoredProcedure(xxx...)
```
error:
```
{"code":"BadRequest","message":"Message: {\"Errors\":[\"The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.\"]}
```
would you be able to apply the same fix made for the ```.deleteDocument``` ? Much appreciated.

**Comment by NateRickard** [comment]
@SogoGolf Can you confirm that the `@PartitionKey` annotation on your model class(es) resolved this issue for you?  If so let's close this... still interested in the PR you mentioned as I can see a situation where passing the value directly would be needed.

**Comment by SogoGolf** [comment]
hi @NateRickard using the annotation tested ok for both createDocument and updateDocument. 

for the executeStoredProcedure ->

this was still throwing the partition key error but let me explain what im trying to do --> I'm calling the stored proc, shaping the data in the stored proc, then returning the payload. the client side object that i'd want to deserialise to, doesn't have/need the partition key field if that makes sense. here's the details:

__model__
```
data class ClubsNearMe(
        val id: String,
        val name: String,
        val metersFromMe: Float
){
    class Deserializer: ResponseDeserializable<Array<ClubsNearMe>> {
        override fun deserialize(content: String): Array<ClubsNearMe>? = Gson().fromJson(content, Array<ClubsNearMe>::class.java)
    }
}
```

im using ```Fuel``` http lib to call an Azure Function for the time being until i work out how to successfully call the stored proc's and get data back. with Fuel, the return payload is being automatically deserialised by Fuel to the model above.

__http call__
```
Fuel.post("https://zzz-js.xxxxxx.net/api/postQuery").jsonBody(query).responseObject(ClubsNearMe.Deserializer()) { request, response, result ->

            val (clubsNearMe, err) = result
etc....
}
```

__stored proc__
```
function getClubsNearMe(prefix) {
    var collection = getContext().getCollection();

    var isAccepted = collection.queryDocuments(
        collection.getSelfLink(),
        `SELECT f.name, ST_DISTANCE(f.location, {'type': 'Point', 'coordinates':[151.2357330322266, -33.77001515278013]}) as metersFromMe FROM etc..") < 50000`,

        function (err, feed, options) {
            if (err) throw err;

            if (!feed || !feed.length) {
                var response = getContext().getResponse();
                response.setBody('no docs found');
            }
            else {
                var response = getContext().getResponse();
                var body = { prefix: prefix, feed: feed };
                response.setBody(JSON.stringify(body));
            }
        });

    if (!isAccepted) throw new Error('The query was not accepted by the server.');
}
```

**Comment by NateRickard** [comment]
@SogoGolf It looks like a partition key header is required if and only if you're doing something within the proc that requires it (like querying).

I'm probably overlapping some of what you started in your PR, but I've added the overloads that will pass this thru correctly and added a passing test (`executeStoredProcedureWithQuery`).

I've pushed out v0.2.2 which should contain these changes.

**Comment by SogoGolf** [comment]
awesome stuff thanks @NateRickard will test this today

**Comment by SogoGolf** [comment]
works like a charm thanks again @NateRickard
